DROP TABLE IF EXISTS "guestlist";
CREATE TABLE guestlist ( id INTEGET PRIMARY KEY, name VARCHAR(30),address VARCHAR(30), nationality VARCHAR(15), phone VARCHAR(15), occupation VARCHAR(15),purpose VARCHAR(20), occupant INTEGER, room VARCHAR(8), intime VARCHAR(30), outtime VARCHAR(30) );
INSERT INTO "guestlist" VALUES(1,'qqq','qqq','India','222','étudiant','Tourism',1,'100','mer. déc. 19 23:45:45 2012','0');
INSERT INTO "guestlist" VALUES(2,'jaloul','jaloul','India','8888','étudiant','Tourism',1,'101','mer. déc. 19 23:48:13 2012','0');
DROP TABLE IF EXISTS "otherorders";
CREATE TABLE otherorders (id INTEGER PRIMARY KEY, time VARCHAR(30), text VARCHAR(40), price INTEGER, guestid INTEGER);
INSERT INTO "otherorders" VALUES(1,'mer. déc. 19 23:49:30 2012','photoo',90,1);
DROP TABLE IF EXISTS "payments";
CREATE TABLE payments ( id INTEGET PRIMARY KEY, time VARCHAR(25), amount INTEGER, guestID INTEGER );
DROP TABLE IF EXISTS "restmenu";
CREATE TABLE restmenu (item VARCHAR(30),price INTEGER);
INSERT INTO "restmenu" VALUES('chorba',10);
DROP TABLE IF EXISTS "restorders";
CREATE TABLE restorders (id INTEGET PRIMARY KEY, item VARCHAR(20), quantity INTEGER, price INTEGER, guestID INTEGER, time VARCHAR(20));
DROP TABLE IF EXISTS "roomcat";
CREATE TABLE roomcat (id INTEGET PRIMARY KEY, item VARCHAR(30), price INTEGER);
INSERT INTO "roomcat" VALUES(1,'singel',300);
INSERT INTO "roomcat" VALUES(2,'chambre double',300);
INSERT INTO "roomcat" VALUES(3,'luxe',200);
DROP TABLE IF EXISTS "roomlist";
CREATE TABLE roomlist (id INTEGET PRIMARY KEY, roomno VARCHAR(5), cat INTEGER, occupied INTEGER);
INSERT INTO "roomlist" VALUES(1,'100',1,1);
INSERT INTO "roomlist" VALUES(2,'101',1,2);
INSERT INTO "roomlist" VALUES(3,'102',1,0);
DROP TABLE IF EXISTS "settings";
CREATE TABLE settings (id INTEGET PRIMARY KEY, key VARCHAR(10), value VARCHAR(40));
INSERT INTO "settings" VALUES(1,'name','jaloul');
INSERT INTO "settings" VALUES(2,'motto','jaloul');
